Bootstrap: docker
From: ubuntu:18.04

%labels
    AUTHOR alarcj137@gmail.com

%environment 
    VARIABLE=MEATBALLVALUE
    export VARIABLE 

%files
    ./root.txt
    ./homeuser.txt /etc/opt

%post
    apt-get update -y && apt-get -y install git wget python3
    mkdir /data
    echo "The post section is where you can install and configure your container..."

%runscript
    echo "\n\n"
    cat /etc/*release
    exec echo "The runscript is the container's default runtime command!"
